name: Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    name: Run Js Tests
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Node Js
        uses: actions/setup-node@v2
        with:
          node-version: v18.12.x

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Run tests
        run: yarn test --coverage
